on:
  push:
    branches: [main]
    
jobs:
  package:
    name: Create packaged archives
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Create zip
      run: zip plg_system_kofi.zip index.html kofi.* en-GB.plg_system_kofi.*
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: plg_system_kofi.zip
        path: plg_system_kofi.zip
