on:
  push:
    branches: [main]
    
jobs:
  package:
    name: Create packaged archives
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - uses: actions/upload-artifact@v3.1.1
      with:
        name: plg_system_kofi
        path: |
          index.html
          kofi.*
          en-GB.plg_system_kofi.*
